[KO-258] Capturing services and persistentVolumes from cluster.
aerospike/aerospike-kubernetes-operator-ctl pull request #5
Opened 2023-08-09 07:01 UTC by tanmayja

2023-08-09 07:47 UTC, abhishekdwivedi3060 requested changes

2023-08-09 07:47 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/resources.go
> +		PVKind:                "persistentvolumes",
Is it possible to filter out required or relevant PVs, maybe using CR storageClass and all?
As PV is a clusterscope resource, there can be 100s PV present in the cluster

2023-08-21 06:48 UTC, abhishekdwivedi3060 requested changes

2023-08-21 06:48 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/collectinfo_util.go
> +	objOutputDir := filepath.Join(rootOutputPath, "summary")
Create constants for all 3 new dir/files name and use those in tests as well

2023-08-21 06:48 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/collectinfo_util.go
> +			logger.Error("could not run command: ", zap.Error(err))
Should continue here, right?

2023-08-21 06:48 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/collectinfo_util.go
> +	cmdMap := make(map[string]*exec.Cmd)
I think we should check if `kubectl` binary is available in the PATH or not before trying to create summary.
Also, if it's not available in the PATH, should we ask for `kubectl` path as param or make it pre-req in our doc ?

2023-08-22 05:09 UTC, tanmayja commented on pkg/collectinfo/collectinfo_util.go
> +				panic(err)
removed conversion

2023-09-05 18:40 UTC, abhishekdwivedi3060 approved these changes

2023-09-05 18:40 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/collectinfo_util.go
> +			volumeName := obj["spec"].(map[string]interface{})["volumeName"].(string)
Check for `volumeName` existence. This will throw panic for pending PVCs

2023-09-05 18:40 UTC, abhishekdwivedi3060 commented on pkg/collectinfo/collectinfo_util.go
> +	pvcNameSet.Insert("NAME")
Please add a comment for this

2023-09-06 08:54 UTC, abhishekdwivedi3060 approved these changes

2023-09-08 10:58 UTC, sud82 approved these changes

2023-09-08 10:59 UTC, merged