KO-251: Added auth sub-command to grant RBAC access
aerospike/aerospike-kubernetes-operator-ctl pull request #6
Opened 2023-08-14 07:55 UTC by abhishekdwivedi3060

TODO: Add test-cases

2023-09-11 14:47 UTC, tanmayja requested changes

2023-09-12 08:34 UTC, tanmayja reviewed
User can give namespace which is not present in cluster. Specially in clustering we make lot of unnecessary info calls for that namespace and error out, can we check namespace existence beforehand to avoid this calls in both subcommands.

2023-09-12 08:37 UTC, tanmayja commented on pkg/auth/auth_suite_test.go
Can we make this file and collecting_suite_test.go common to both test suite to avoid duplication?

2023-09-15 09:28 UTC, abhishekdwivedi3060 commented on pkg/auth/auth_suite_test.go
IMO, it would be better to keep these package level test-suites separate as they don't have any common functionality to be tested under one suite. Instead, created a testutils pkg for  common test related funcs  for reusability

2023-09-19 06:49 UTC, tanmayja approved these changes

2023-09-28 09:21 UTC, sud82 approved these changes

2023-09-28 09:22 UTC, merged